val builder = new collection.mutable.StringBuilder
builder ++= ("<" + "a" + " " + "href" + "=" + """'/contact'""" + ">")
builder ++= ("contact")
builder ++= ("</" + "a" + ">")
builder ++= ("<" + "a" + " " + "href" + "=" + """'/save'""" + " " + "class" + "=" + """'button'""" + ">")
builder ++= ("save")
builder ++= ("</" + "a" + ">")
builder ++= ("<" + "a" + " " + "foo" + "" + " " + "bar" + "" + " " + "baz" + "" + ">")
builder ++= ("</" + "a" + ">")
builder ++= ("<" + "a" + " " + "foo" + "=" + """'foo, bar, baz'""" + " " + "bar" + "=" + "'" + 1 + "'" + ">")
builder ++= ("</" + "a" + ">")
val bar = (if(true) "1" else "0")
builder ++= ("<" + "a" + " " + "foo" + "=" + """'((foo))'""" + " " + "bar" + "=" + "'" + bar + "'" + ">")
builder ++= ("</" + "a" + ">")
builder ++= ("<" + "select" + "" + ">")
builder ++= ("<" + "option" + " " + "value" + "=" + """'foo'""" + " " + "selected" + "" + ">")
builder ++= ("Foo")
builder ++= ("</" + "option" + ">")
builder ++= ("<" + "option" + " " + "selected" + "" + " " + "value" + "=" + """'bar'""" + ">")
builder ++= ("Bar")
builder ++= ("</" + "option" + ">")
builder ++= ("</" + "select" + ">")
builder ++= ("<" + "a" + " " + "foo" + "=" + """"class:"""" + ">")
builder ++= ("</" + "a" + ">")
builder ++= ("<" + "input" + " " + "pattern" + "=" + """'\\S+'""" + ">")
builder ++= ("</" + "input" + ">")

builder.toString
